--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mikyle/Pictures/wallpaperflare.com_wallpaper (6).jpg"

-- Special
background="#0b0c19"
foreground="#f6eee2"
cursor="#f6eee2"

-- Colors
color0="#0b0c19"
color1="#666B85"
color2="#A3A0A2"
color3="#DCBAA6"
color4="#C5BFC8"
color5="#CAC5CD"
color6="#EBD9CA"
color7="#f6eee2"
color8="#aca69e"
color9="#666B85"
color10="#A3A0A2"
color11="#DCBAA6"
color12="#C5BFC8"
color13="#CAC5CD"
color14="#EBD9CA"
color15="#f6eee2"
