# Shell variables
# Generated by 'wal'
wallpaper='/home/mikyle/Pictures/wallpaperflare.com_wallpaper (6).jpg'

# Special
background='#0b0c19'
foreground='#f6eee2'
cursor='#f6eee2'

# Colors
color0='#0b0c19'
color1='#666B85'
color2='#A3A0A2'
color3='#DCBAA6'
color4='#C5BFC8'
color5='#CAC5CD'
color6='#EBD9CA'
color7='#f6eee2'
color8='#aca69e'
color9='#666B85'
color10='#A3A0A2'
color11='#DCBAA6'
color12='#C5BFC8'
color13='#CAC5CD'
color14='#EBD9CA'
color15='#f6eee2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
